Update mmsms
1. Rewrote almost all source code for efficiency.
2. Added a prompt to confirm delete all messages.
3. Removed the log file because it wasn't very useful.

diff --git a/mmsms b/mmsms
--- a/mmsms
+++ b/mmsms
@@ -1,63 +1,87 @@
 #!/bin/bash
+# ModemManager SMS Client v1.0
 # Created by Satria K.
-# Forked from https://github.com/frizkyiman/
+# Homepage : https://github.com/satriakanda/mmsms
 
-modem_info=$(mmcli -L | awk -F']' '/Modem/{print $2}' | sed 's/^[ \t]*//')
-modem_id=$(mmcli -L | awk -F'/Modem/' 'NF>1{print $2; exit}' | awk '{print $1}')
-sms_list=$(mmcli -m "$modem_id" --messaging-list-sms)
-
-function read() {
-    log_file="/root/sms_message.log"
-    max_file_size=524288 #0.5MB
-    [ ! -d "$log_file" ] && touch "$log_file"
-
-    if [ "$(mmcli -L)" == "No modems were found" ]; then
-        echo "Error: Modem not found."
-        exit 1
-    elif [ "$sms_list" = "No sms messages were found" ]; then
-        echo "No SMS messages were found from modem [$modem_info]"
-        exit 0
+mmcli_info=$(mmcli -L 2>&1);
+if [[ "$mmcli_info" == "No modems were found" ]]; then
+    echo "Error: Modem is not detected by ModemManager"
+    exit 1
+else
+    if [[ "$mmcli_info" =~ ((/org/freedesktop/ModemManager[0-9]+)/Modem/([0-9]+) \[([^\]]+?)\] (.+)) ]]; then
+        modem_path=${BASH_REMATCH[2]}
+        modem_id=${BASH_REMATCH[3]}
+        modem_manufacturer=${BASH_REMATCH[4]}
+        modem_model=${BASH_REMATCH[5]}
     else
-        echo "SMS received from modem [$modem_info]"
-        echo "SMS Message list:"
-        echo "$sms_list"
+        echo "Error: Modem is not recognized"
+        exit 1
+    fi
+fi
+
+function read_sms() {
+    sms_list=$(mmcli -m "$modem_id" --messaging-list-sms)
+    if [[ "$sms_list" == "No sms messages were found" ]]; then
+        echo "No SMS messages were found from modem [$modem_model]"
+    else
+        sms_count=$(echo "$sms_list" | wc -l)
+        echo "Total $sms_count SMS messages were found from modem [$modem_model]"
+        n=0
         IFS=$'\n'
         rows=($sms_list)
         for sms_info in "${rows[@]}"; do
-            sms_id=$(echo "$sms_info" | awk -F'/SMS/' 'NF>1{print $2}' | awk '{print $1}')
+            ((n++))
+            (( $n > 1 )) && echo ""
+            sms_id=$(echo "$sms_info" | grep /SMS/ | sed -r "s/.+\/SMS\/([0-9]+).+/\1/")
+            echo "  [$n] SMS ID Number: $sms_id"
             message=$(mmcli -m "$modem_id" --sms "$sms_id")
             if [ -n "$message" ]; then
-                echo "$message" | tee temp_message.log
-                cat "$log_file" >> temp_message.log && mv temp_message.log "$log_file"
+                if [[ "$message" == *"pdu type: status-report"* ]]; then
+                    echo "      pdu type: status-report"
+                elif [[ "$message" == *"delivery report: requested"* ]]; then
+                    echo "      delivery report: requested"
+                else
+                    echo "$message"
+                fi
             fi
         done
-        exit 0
     fi
 }
 
-function delete() {
-    ## Cek jenis modem
+function delete_sms() {
     if [ -n "${1}" ]; then
-        echo -n "Delete SMS ID: ${1} => "
-        mmcli -m $modem_id --messaging-delete-sms=/org/freedesktop/ModemManager1/SMS/$1
+        echo -n "Deleting SMS ID Number: ${1} => "
+        mmcli -m ${modem_id} --messaging-delete-sms=${modem_path}/SMS/${1}
     else
-        echo "Delete all SMS from modem [$modem_info]"
-        IFS=$'\n'
-        rows=($sms_list)
-        for sms_info in "${rows[@]}"; do
-            sms_id=$(echo "$sms_info" | awk -F'/SMS/' 'NF>1{print $2}' | awk '{print $1}')
-            if [ -n "$sms_id" ]; then
-                echo -n "Delete SMS ID: $sms_id => "
-                mmcli -m $modem_id --messaging-delete-sms=/org/freedesktop/ModemManager1/SMS/$sms_id
+        sms_list=$(mmcli -m "$modem_id" --messaging-list-sms)
+        if [[ "$sms_list" == "No sms messages were found" ]]; then
+            echo "No SMS messages were found from modem [$modem_model]"
+        else
+            read -r -p "Are you sure to delete all SMS messages? [y/N] " response
+            if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
+                sms_count=$(echo "$sms_list" | wc -l)
+                echo "Delete all $sms_count SMS messages from modem [$modem_model]"
+                n=0
+                IFS=$'\n'
+                rows=($sms_list)
+                for sms_info in "${rows[@]}"; do
+                    ((n++))
+                    sms_id=$(echo "$sms_info" | grep /SMS/ | sed -r "s/.+\/SMS\/([0-9]+).+/\1/")
+                    if [ -n "$sms_id" ]; then
+                        echo -n "[$n] Deleting SMS ID Number: $sms_id => "
+                        mmcli -m ${modem_id} --messaging-delete-sms=${modem_path}/SMS/${sms_id}
+                    else
+                        echo "No SMS messages were found from modem [$modem_model]"
+                    fi
+                done
             else
-                echo "No SMS found!"
+                echo "Cancelled"
             fi
-        done
+        fi
     fi
-    exit 0
 }
 
-function send() {
+function send_sms() {
     to="${1}"
     if [[ ! "$to" =~ ^\+?[0-9]+$ ]]; then
         echo "Please provide the receiver number (08xxxx or +628xxx)"
@@ -68,9 +92,10 @@ function send() {
         echo "Please provide the message"
         exit 1
     fi
-    sms_info=$(mmcli -m "$modem_id"  --messaging-create-sms="number='${to}',text='${message}'")
-    sms_id=$(echo "$sms_info" | awk -F'/SMS/' 'NF>1{print $2}' | awk '{print $1}')
-    mmcli -s $sms_id --send
+    sms_create=$(mmcli -m "$modem_id"  --messaging-create-sms="number='${to}',text='${message}'")
+    sms_id=$(echo "$sms_create" | grep /SMS/ | sed -r "s/.+\/SMS\/([0-9]+)/\1/")
+    echo "SMS ID Number: $sms_id"
+    mmcli -s ${sms_id} --send
 }
 
 function usage() {
@@ -78,26 +103,32 @@ function usage() {
     echo "#####   ModemManager SMS Client v1.0  #####"
     echo "#####       Created by Satria K.      #####"
     echo "###########################################"
-    echo "Usage:
-  -r   Read all SMS
-  -s   Send SMS. Use format: -s [phonenumber] [message]
-  -d   Delete all SMS. Use -d [number] to delete a spesific SMS with ID number"
+    echo "Model        : $modem_model"
+    echo "Manufacturer : $modem_manufacturer"
+    echo "Path         : $modem_path"
+    echo "Modem ID     : $modem_id"
+    echo "Usage :
+  -r  :  Read all SMS messages.
+  -s  :  Send a SMS message. Use format: -s [phonenumber] [message]
+         Example: mmsms -s 08123456789 Hello, how are you?
+  -d  :  Delete all SMS messages. Use -d [number] to delete a spesific SMS with id number.
+         Example 1: mmsms -d (delete all SMS messages)
+         Example 2: mmsms -d 32 (delete a SMS message with id number 32)"
 }
 
 case "${1}" in
     -r)
-        read
+        read_sms
         ;;
     -d)
         shift
-        delete "${1}"
+        delete_sms "${1}"
         ;;
     -s)
         shift
-        send "${@}"
+        send_sms "${@}"
       ;;
     *)
       usage
       ;;
 esac
-
